const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

class PDFGenerator {
  constructor() {
    this.doc = new PDFDocument({
      size: 'A4',
      margin: 50,
      info: {
        Title: 'Kanchkura College',
        Creator: 'Kanchkura ERP System',
      },
    });
  }

  generateReceipt(payment, student, collectedBy) {
    this.doc.fontSize(20).font('Helvetica-Bold').text('KANCHKURA COLLEGE', { align: 'center' });
    this.doc.fontSize(10).font('Helvetica').text('Official Payment Receipt', { align: 'center' });
    this.doc.moveDown(0.5);
    this.doc.fontSize(8).text('Kanchkura, Kishoreganj, Bangladesh', { align: 'center' });
    this.doc.moveDown();

    this.doc.moveTo(50, this.doc.y).lineTo(545, this.doc.y).stroke('#333');
    this.doc.moveDown();

    this.doc.fontSize(10);
    this.doc.text(`Receipt No: ${payment.receipt_number}`, { align: 'right' });
    this.doc.text(`Date: ${payment.payment_date}`, { align: 'right' });
    this.doc.text(`Time: ${payment.payment_time}`, { align: 'right' });
    this.doc.moveDown();

    this.doc.moveTo(50, this.doc.y).lineTo(545, this.doc.y).stroke('#999');
    this.doc.moveDown(0.5);

    this.doc.fontSize(11).font('Helvetica-Bold').text('Student Information');
    this.doc.fontSize(10).font('Helvetica');
    this.doc.text(`Name: ${student?.full_name || 'N/A'}`);
    this.doc.text(`Student ID: ${student?.student_id || 'N/A'}`);
    this.doc.text(`Class: ${student?.class_id || 'N/A'} | Roll: ${student?.roll_number || 'N/A'}`);
    this.doc.moveDown();

    this.doc.moveTo(50, this.doc.y).lineTo(545, this.doc.y).stroke('#999');
    this.doc.moveDown(0.5);

    this.doc.fontSize(11).font('Helvetica-Bold').text('Payment Details');
    this.doc.fontSize(10).font('Helvetica');
    this.doc.text(`Fee Type: ${payment.fee_type}`);
    this.doc.text(`Amount: ৳${parseFloat(payment.amount).toLocaleString()}`);
    this.doc.text(`Paid: ৳${parseFloat(payment.paid_amount).toLocaleString()}`);
    if (parseFloat(payment.discount_amount) > 0) {
      this.doc.text(`Discount: ৳${parseFloat(payment.discount_amount).toLocaleString()}`);
    }
    if (parseFloat(payment.due_amount) > 0) {
      this.doc.text(`Due: ৳${parseFloat(payment.due_amount).toLocaleString()}`);
    }
    this.doc.text(`Payment Method: ${payment.payment_method}`);
    this.doc.moveDown(0.5);

    this.doc.moveTo(50, this.doc.y).lineTo(545, this.doc.y).stroke('#999');
    this.doc.moveDown();

    this.doc.fontSize(10).font('Helvetica-Bold');
    this.doc.text(`Status: ${payment.status.toUpperCase()}`, { align: 'right' });
    this.doc.moveDown();

    this.doc.fontSize(8).font('Helvetica').fillColor('#666');
    this.doc.text(`Collected by: ${collectedBy?.name || 'System'}`, { align: 'left' });
    this.doc.moveDown();

    this.doc.fillColor('#000');
    this.doc.moveTo(50, this.doc.y).lineTo(545, this.doc.y).stroke('#333');
    this.doc.moveDown();

    this.doc.fontSize(9).fillColor('#666').text(
      'Thank you for your payment.\nThis is a computer-generated receipt.\nFor queries, contact the accounts office.',
      { align: 'center' }
    );

    return this.doc;
  }

  generateResultSheet(results, student, examType) {
    this.doc.fontSize(18).font('Helvetica-Bold').text('KANCHKURA COLLEGE', { align: 'center' });
    this.doc.fontSize(12).text('Student Result Sheet', { align: 'center' });
    this.doc.moveDown();

    this.doc.fontSize(10);
    this.doc.text(`Student: ${student?.full_name || 'N/A'}`);
    this.doc.text(`Student ID: ${student?.student_id || 'N/A'}`);
    this.doc.text(`Exam Type: ${examType}`);
    this.doc.moveDown();

    const tableTop = this.doc.y;
    const columns = [50, 150, 230, 310, 380, 450];
    const headers = ['Subject', 'Marks', 'GPA', 'Grade'];

    this.doc.fontSize(10).font('Helvetica-Bold');
    headers.forEach((h, i) => this.doc.text(h, columns[i], tableTop));
    this.doc.moveDown();

    let y = this.doc.y;
    this.doc.fontSize(10).font('Helvetica');
    for (const r of results) {
      this.doc.text(r.subject?.name || 'N/A', columns[0], y);
      this.doc.text(String(r.total_mark), columns[1], y);
      this.doc.text(String(r.gpa), columns[2], y);
      this.doc.text(r.grade, columns[3], y);
      y += 20;
    }

    this.doc.moveDown();
    this.doc.moveTo(50, y + 10).lineTo(545, y + 10).stroke();
    this.doc.fontSize(9).fillColor('#666').text('Generated by Kanchkura ERP System', { align: 'center' });

    return this.doc;
  }

  save(filepath) {
    return new Promise((resolve, reject) => {
      const dir = path.dirname(filepath);
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

      const stream = fs.createWriteStream(filepath);
      this.doc.pipe(stream);
      this.doc.end();
      stream.on('finish', () => resolve(filepath));
      stream.on('error', reject);
    });
  }

  pipe(res) {
    this.doc.pipe(res);
    return this.doc;
  }
}

module.exports = { PDFGenerator };
